window.gameInstances.dino = {
    canvas: document.getElementById('dino-canvas'), 
    music: document.getElementById('dino-music'), 
    ctx: null, dino: {}, obstacles: [], gameSpeed: 5, gravity: 0.6, score: 0, frameCount: 0, paused: false, gameOver: false, loop: null,
    init() { this.ctx = this.canvas.getContext('2d'); this.reset(); window.addEventListener('keydown', this.handleInput.bind(this)); window.addEventListener('keyup', this.handleKeyUp.bind(this)); },
    reset() { this.dino = { x: 50, y: 0, width: 44, height: 47, dy: 0, jumpPower: 15, grounded: true, isDucking: false, runFrame: 0 }; this.obstacles = []; this.score = 0; this.gameSpeed = 5; this.gameOver = false; this.frameCount = 0; this.music.currentTime = 0; },
    handleInput(e) { if (window.activeGame !== 'dino' || this.paused) return; if ((e.key === ' ' || e.key === 'ArrowUp') && this.dino.grounded) { this.dino.dy = -this.dino.jumpPower; this.dino.grounded = false; } else if (e.key === 'ArrowDown') { this.dino.isDucking = true; } },
    handleKeyUp(e) { if (window.activeGame !== 'dino' || this.paused) return; if (e.key === 'ArrowDown') { this.dino.isDucking = false; } },
    update() { if (this.paused || this.gameOver) return; this.frameCount++; this.score++; this.dino.dy += this.gravity; this.dino.y += this.dino.dy; const groundY = this.canvas.height - 20; if (this.dino.y + this.dino.height > groundY) { this.dino.y = groundY - this.dino.height; this.dino.dy = 0; this.dino.grounded = true; } if (this.dino.isDucking) { this.dino.height = 25; } else { this.dino.height = 47; } if (this.frameCount % 5 === 0) { this.dino.runFrame = (this.dino.runFrame + 1) % 2; } if (this.frameCount % Math.max(30, (100 - this.gameSpeed * 5)) === 0 && Math.random() < 0.5) { const type = Math.random() > 0.3 ? 'cactus' : 'bird'; if (type === 'cactus') { this.obstacles.push({ x: this.canvas.width, y: groundY - 50, width: 25, height: 50, type }); } else { this.obstacles.push({ x: this.canvas.width, y: groundY - (Math.random() > 0.5 ? 60 : 100), width: 45, height: 30, type, frame: 0 }); } } this.obstacles.forEach((obs, i) => { obs.x -= this.gameSpeed; if (obs.type === 'bird' && this.frameCount % 10 === 0) obs.frame = (obs.frame + 1) % 2; if (obs.x + obs.width < 0) this.obstacles.splice(i, 1); if (this.dino.x < obs.x + obs.width && this.dino.x + this.dino.width > obs.x && this.dino.y < obs.y + obs.height && this.dino.y + this.dino.height > obs.y) { this.gameOver = true; window.playGameOverSound(); } }); if (this.frameCount % 200 === 0) this.gameSpeed += 0.2; },
    drawDino() { const c = this.ctx; const d = this.dino; c.fillStyle = '#4b5563'; if (!this.dino.grounded) { c.fillRect(d.x, d.y, d.width, d.height); } else if (this.dino.isDucking) { c.fillRect(d.x, d.y, 58, d.height); } else { c.fillRect(d.x, d.y, d.width, d.height); } },
    drawCactus(obs) { this.ctx.fillStyle = '#166534'; this.ctx.fillRect(obs.x, obs.y, obs.width, obs.height); },
    drawBird(obs) { this.ctx.fillStyle = '#374151'; this.ctx.fillRect(obs.x, obs.y, obs.width, obs.height); },
    draw() { this.ctx.fillStyle = '#f3f4f6'; this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height); this.ctx.fillStyle = '#4b5563'; this.ctx.fillRect(0, this.canvas.height - 20, this.canvas.width, 20); this.drawDino(); this.obstacles.forEach(obs => { if (obs.type === 'cactus') this.drawCactus(obs); else this.drawBird(obs); }); this.ctx.fillStyle = '#4b5563'; this.ctx.font = '24px "VT323"'; this.ctx.textAlign = 'right'; this.ctx.fillText(`SCORE: ${Math.floor(this.score/5)}`, this.canvas.width - 20, 30); if (this.gameOver) { this.ctx.fillStyle = 'rgba(0, 0, 0, 0.5)'; this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height); this.ctx.fillStyle = '#f3f4f6'; this.ctx.font = '32px "VT323"'; this.ctx.textAlign = 'center'; this.ctx.fillText('GAME OVER', this.canvas.width / 2, this.canvas.height / 2); } },
    gameLoop() { if (!this.paused) { this.update(); this.draw(); } this.loop = requestAnimationFrame(this.gameLoop.bind(this)); },
    start() { this.paused = false; if(this.loop) cancelAnimationFrame(this.loop); this.loop = requestAnimationFrame(this.gameLoop.bind(this)); window.safePlay(this.music); },
    stop() { if(this.loop) cancelAnimationFrame(this.loop); this.loop = null; this.paused = true; this.music.pause(); document.body.style.overflow = 'auto';},
    togglePause() { this.paused = !this.paused; if (!this.gameOver && !this.paused) this.music.play(); else this.music.pause(); }
};